name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  exercises:
    name: Run tests
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm run test
